const GDR =[
    {
        title: "The Elder Scrolls V: Skyrim",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 49.99,
        image: "https://static-it.gamestop.it/images/products/271728/3max.jpg",
        description: "Esplora un vasto mondo aperto ricco di avventure, segreti e pericoli. In The Elder Scrolls V: Skyrim, vestirai i panni di un eroe del destino, impegnato in un'epica battaglia contro draghi e forze oscure. Combatti, fai scelte morali, migliora le tue abilità e scopri una trama intricata mentre ti immergi nella ricchezza di un mondo fantastico.",
      },
      {
        title: "Fallout 4",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 39.99,
        image: "https://m.media-amazon.com/images/I/81aXmeRnvnL._AC_SX385_.jpg",
        description: "Ambientato in un mondo post-apocalittico devastato dalla guerra nucleare, Fallout 4 ti mette alla prova come sopravvissuto in un deserto irradiato. Combatti creature mutanti, esplora insediamenti abbandonati, crea armi e armature, prendi decisioni che influenzeranno il destino delle persone che incontri e scopri un'avvincente storia di sopravvivenza e rinascita.",
      },
      {
        title: "Final Fantasy XV",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 59.99,
        image: "https://m.media-amazon.com/images/I/816QDLTi+aL._AC_UL600_FMwebp_QL65_.jpg",
        description: "Entra in un mondo di fantasia epica e magia in Final Fantasy XV. Segui il principe Noctis e i suoi fedeli compagni in un viaggio per reclamare il suo trono e salvare il suo regno da un'oscura minaccia. Combatti contro potenti nemici, esplora ambientazioni mozzafiato e immergiti in un'emozionante storia di amicizia, sacrificio e redenzione.",
      },
      {
        title: "Dark Souls III",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 29.99,
        image: "https://m.media-amazon.com/images/I/61nNjBcptuL._AC_UL600_FMwebp_QL65_.jpg",
        description: "Sfida la tua determinazione e abilità in un mondo oscuro e brutale. Dark Souls III è un gioco di ruolo e azione che mette alla prova i giocatori con nemici spietati, boss imponenti e un gameplay tattico e impegnativo. Esplora ambientazioni gotiche, migliora il tuo personaggio e affronta sfide mortali in una delle serie più celebrate e stimolanti del genere.",
      },
      {
        title: "Mass Effect 2",
        consoleName: "Xbox One",
        genre: "GDR",
        price: 19.99,
        image: "https://m.media-amazon.com/images/I/81xQLCsWe6L._AC_UL600_FMwebp_QL65_.jpg",
        description: "In Mass Effect 2, ti unirai alla squadra di una nave spaziale e intraprenderai un'avventura emozionante attraverso la galassia. Combatti contro minacce extraterrestri, prendi decisioni che influenzano la trama e il destino dei personaggi e scopri una storia coinvolgente ricca di azione, intrighi e amicizia. Esplora mondi alieni, personalizza il tuo personaggio e forma legami con i tuoi compagni di squadra in un'epica saga di fantascienza.",
      },
      {
        title: "Dragon Age: Inquisition",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 39.99,
        image: "https://m.media-amazon.com/images/I/91X8W3KNuCL._AC_UL600_FMwebp_QL65_.jpg",
        description: "Diventa un eroe leggendario e salva il mondo da un'oscura minaccia in Dragon Age: Inquisition. In questo gioco di ruolo epico, formerai e guiderai un gruppo di personaggi unici, affrontando sfide, combattendo mostri e prendendo decisioni che avranno conseguenze durature. Esplora un vasto mondo aperto, fai alleanze o intraprendi guerre, scopri segreti e svela la verità dietro il caos che minaccia il tuo mondo.",
      },
      {
        title: "Persona 5",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 49.99,
        image: "https://m.media-amazon.com/images/I/81RYPL46ZhL._AC_UL600_FMwebp_QL65_.jpg",
        description: "In Persona 5, vivi una doppia vita come studente di giorno e ladro misterioso di notte. Esplora il lato oscuro di Tokyo, combatti contro forze malvagie, risolvi enigmi e cerca di ristabilire la giustizia in un mondo corrotto. Con uno stile unico, una colonna sonora coinvolgente e una trama avvincente che affronta temi come l'amicizia, l'identità e il potere, Persona 5 offre un'esperienza di gioco indimenticabile.",
      },
      {
        title: "Divinity: Original Sin 2",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 59.99,
        image: "https://m.media-amazon.com/images/I/71FFRN75-ZS._AC_UL600_FMwebp_QL65_.jpg",
        description: "Divinity: Original Sin 2 è un RPG di avventura e fantasia in cui assumi il ruolo di un protagonista con abilità magiche uniche. Esplora un vasto mondo aperto, affronta combattimenti tattici e risolvi enigmi complessi. Il gioco offre una libertà di scelta senza precedenti, permettendoti di plasmare il destino del tuo personaggio e influenzare il mondo circostante in modi sorprendenti.",
      },
      {
        title: "The Legend of Zelda: Breath of the Wild",
        consoleName: "Nintendo Switch",
        genre: "GDR",
        price: 59.99,
        image: "https://m.media-amazon.com/images/I/91zYKmF4jjL._AC_UL600_FMwebp_QL65_.jpg",
        description: "Esplora un vasto regno di avventure, misteri e pericoli in The Legend of Zelda: Breath of the Wild. In questo gioco di ruolo d'azione, vestirai i panni di Link, l'eroe leggendario, e ti imbarcherai in un viaggio epico per sconfiggere un'antica minaccia e salvare la principessa Zelda. Esplora paesaggi mozzafiato, risolvi enigmi, affronta nemici e scopri la storia di Hyrule in uno dei capitoli più acclamati della serie.",
      },
      {
        title: "Bloodborne",
        consoleName: "PlayStation 4",
        genre: "GDR",
        price: 39.99,
        image: "https://m.media-amazon.com/images/I/81TYwxDpw5L._AC_UL600_FMwebp_QL65_.jpg",
        description: "Entra in un mondo gotico e tenebroso, infestato da creature malvagie e pericolose, in Bloodborne. In questo gioco di ruolo e azione, affronta combattimenti intensi e veloci, esplora ambientazioni inquietanti e scopri una trama oscura e misteriosa. Con una difficoltà impegnativa e un'atmosfera unica, Bloodborne offre un'esperienza coinvolgente per i fan dei giochi di ruolo e dei giochi d'azione.",
      },
]

export default GDR;